[package]
name = "bn254_fixedmul"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4"
ark-bn254 = "0.4"
rand = "0.8"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench"
harness = false